apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-service
  labels:
    app: player-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-service
  template:
    metadata:
      labels:
        app: player-service
    spec:
      containers:
        - name: player-service
          image: player-service:latest
          ports:
            - containerPort: 9091